name: linux
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perl:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        perl-version:
          - '5.14'
          - '5.16'
          - '5.18'
          - '5.20'
          - '5.22'
          - '5.30'
          - '5.32'
    container:
      image: perl:${{ matrix.perl-version }}
    steps:
      - uses: actions/checkout@v2
      - name: perl -V
        run: perl -V
      - name: Fix ExtUtils::MakeMaker (for Perl 5.16 and 5.18)
        run: cpanm -n App::cpanminus ExtUtils::MakeMaker
      - name: Install author dependencies
        run: |
          cpanm Archive::Tar
          cpanm Archive::Zip
          cpanm Dist::Zilla
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
      - name: Install project dependencies
        run: |
          dzil listdeps | cpanm
      - name: Run tests
        run: VALIANT_DEBUG=3 prove -lr t
      - name: Code coverage
        env: # Or as an environment variable
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: cover -test -report codecov

