name: Windows testing and code coverage
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest']
    runs-on: ${{ matrix.os }}
    name: Perl  on ${{ matrix.os }}i
    steps:
      - uses: actions/checkout@v2
      - name: Set up Perl
        run: |
          choco install strawberryperl
          echo "C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin" >> $GITHUB_PATH
      - name: perl -V
        run: perl -V
      - name: Install author/build dependencies
        run: |
          curl -L http://cpanmin.us | perl - --verbose --reinstall --notest App::cpanminus
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecovbash
          cpanm --quiet --notest --skip-satisfied Archive::Tar
          cpanm --quiet --notest --skip-satisfied Archive::Zip
      - name: Install project dependencies
        run: |
          cpanm --verbose --installdeps .
      - name: Run tests
        run: prove -lr t
      - name: Code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          PERL5OPT=-MDevel::Cover=+ignore,^t,prove$  prove -j9 -lr t
          cover -report codecovbash
          curl -s https://codecov.io/bash | bash
