name: Windows testing and code coverage
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  build:
    strategy:
      matrix:
        os: ['windows-latest']
    runs-on: ${{ matrix.os }}
    name: Perl  on ${{ matrix.os }}i
    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: 'latest'
          distribution: ${{ ( startsWith( matrix.runner, 'windows-' ) && 'strawberry' ) || 'default' }}
          install-modules-with: cpanm
          install-modules-args: --with-develop --with-configure
          enable-modules-cache: false
      - name: perl -V
        run: perl -V
      - name: Install cpanm
        run: curl -L http://cpanmin.us | perl - --verbose --reinstall --notest App::cpanminus
      - name: Install author/build dependencies
        run: |
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecov
          cpanm --quiet --notest --skip-satisfied Devel::Cover::Report::Codecovbash
          cpanm --quiet --notest --skip-satisfied Archive::Tar
          cpanm --quiet --notest --skip-satisfied Archive::Zip
      - name: Install project dependencies
        run: |
          cpanm --verbose --installdeps .
      - name: Run tests
        run: prove -lr t
      - name: Code coverage
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        run: |
          PERL5OPT=-MDevel::Cover=+ignore,^t,prove$  prove -lr t
          cover -report codecovbash
          curl -s https://codecov.io/bash | bash
